export const notes: string[] = [
  "The genuine kindness you show to everyone around you.",
  "Your ability to bring a smile to my face, even on hard days.",
  "The way you stand by the people you care about.",
  "How you always listen — really listen — when I need to talk.",
  "Your infectious laughter that lights up the entire room.",
  "The way you celebrate the small victories in life.",
  "Your patience and understanding when things get stressful.",
  "How reliable you are; I know I can always count on you.",
  "Your unique perspective and the way you look at the world.",
  "The quiet strength you show during difficult moments.",
  "Your generosity, always willing to share what you have.",
  "How you make ordinary, everyday moments feel special.",
  "Your honesty, even when the truth is hard to say.",
  "The creative energy you bring to everything you do.",
  "Your encouraging words when I doubt myself.",
  "The passion you have for the things you care about.",
  "How you make everyone feel included and welcome.",
  "Your loyalty and dedication to your relationships.",
  "The thoughtful little gestures you do without expecting anything back.",
  "Your ability to forgive and move forward.",
  "How you keep going even when things get tough.",
  "Your curiosity and love for learning new things.",
  "The way you respect other people's boundaries.",
  "Your calm presence that makes stressful situations easier.",
  "How you always remember birthdays and special milestones.",
  "Your willingness to help out without being asked.",
  "The way you show up, physically and emotionally, for others.",
  "Your courage to speak up for what is right.",
  "The respect you show to people from all walks of life.",
  "How you appreciate the beauty in small, simple things.",
  "Your determination to grow and improve every day.",
  "The advice you give, which is always thoughtful and wise.",
  "How you stay true to yourself no matter what.",
  "The positive attitude you try to keep even when challenged.",
  "Your humility and willingness to admit when you're wrong.",
  "The way you keep your promises.",
  "How you make this world a kinder place just by being in it.",
  "Your ability to find solutions instead of just complaining.",
  "The care you take in keeping our conversations meaningful.",
  "How you welcome feedback and strive to understand others.",
  "Your sense of adventure and openness to new experiences.",
  "The way you support my choices, even when you don't fully agree.",
  "Your sense of responsibility and accountability.",
  "How you respect my privacy and let me have my space.",
  "Your appreciation for deep, honest conversations.",
  "The warmth in your greetings every time we meet.",
  "How you respect the time of others and are always punctual.",
  "Your clean, organized way of handling tasks.",
  "The way you look out for the safety and well-being of others.",
  "Your simple, down-to-earth nature.",
  "How you keep long-term connections alive.",
  "Your focus on what truly matters in life.",
  "The way you show gratitude for the things others do for you.",
  "Your ability to remain calm under pressure.",
  "How you don't judge others for their mistakes.",
  "Your willingness to step out of your comfort zone.",
  "The empathy you have for people going through hard times.",
  "How you bring peace and harmony wherever you go.",
  "Your commitment to doing things right, not just fast.",
  "The way you inspire me to be a better person.",
  "How you never speak ill of others behind their back.",
  "Your ability to keep a secret and protect my trust.",
  "The focus you have when working on something you care about.",
  "Your capacity to apologize sincerely when needed.",
  "How you respect elders and show kindness to kids.",
  "The way you handle disagreements with maturity.",
  "Your love for planning and organizing memorable days.",
  "How you stay grounded despite your achievements.",
  "The way you protect and care for your family.",
  "Your appreciation for good food and shared meals.",
  "How you always make time for the people you value.",
  "Your clear, direct way of communicating.",
  "The way you show trust in my abilities.",
  "How you encourage healthy habits and self-care.",
  "Your support during career choices and changes.",
  "The way you appreciate quiet moments of silence together.",
  "How you pay attention to the small details of my day.",
  "Your positive influence on my thoughts and decisions.",
  "The way you look for the silver lining in bad situations.",
  "How you appreciate others' work and praise them openly.",
  "Your respect for traditions and meaningful memories.",
  "The way you handle success with grace and humility.",
  "How you make me laugh with your unique sense of humor.",
  "Your willingness to share your own life stories with me.",
  "The support you show for my hobbies and creative pursuits.",
  "How you never make me feel like a burden.",
  "Your ability to offer help without making others feel small.",
  "The way you appreciate custom gifts and cards.",
  "How you stand firm on your core moral principles.",
  "Your warm smile that always makes me feel comfortable.",
  "The way you defend the weak and stand up to unfairness.",
  "How you always remember my favorite things.",
  "Your focus on building a peaceful and happy life.",
  "The way you make any space feel cozy and welcoming.",
  "How you value quality time over material things.",
  "Your respectful behavior in public and private.",
  "The way you check in on me when I've had a busy day.",
  "Your clear, healthy boundaries.",
  "The way you handle daily challenges with resilience.",
  "Just you. Your unique, wonderful presence in my life."
];